App\Entity\Player:
    attributes:
        id:
            groups:
                - me:read
        user:
            groups:
                - me:read
        tempUser:
            groups:
                - me:read
        dead:
            groups:
                - me:read
        game:
            groups:
                - me:read
