App\Entity\Role:
    attributes:
        id:
            groups:
                - role:read
                - role:list
                - game:read
        type:
            groups:
                - role:read
                - role:list
                - role:write
                - game:read
        name:
            groups:
                - role:read
                - role:list
                - role:write
                - game:read
        description:
            groups:
                - role:read
                - role:write
        ability:
            groups:
                - role:read
                - role:write
        pictureName:
            groups:
                - role:read
                - role:list
                - role:files:write
        picture:
            groups:
                - role:files:write
        minPlayers:
            groups:
                - role:read
                - role:write
        maxPerGame:
            groups:
                - role:read
                - role:write
        teams:
            groups:
                - role:read
                - role:list
                - role:write
