App\Entity\Role:
    attributes:
        id:
            groups:
                - role:read
                - role:list
                - game:read
                - me:player:read
                - homepage:read
        type:
            groups:
                - role:read
                - role:list
                - role:write
                - game:read
                - me:player:read
                - homepage:read
        name:
            groups:
                - role:read
                - role:list
                - role:write
                - game:read
                - me:player:read
                - homepage:read
        description:
            groups:
                - role:read
                - role:write
                - me:player:read
        ability:
            groups:
                - role:read
                - role:write
                - me:player:read
        pictureName:
            groups:
                - role:read
                - role:list
                - role:files:write
                - me:player:read
                - homepage:read
        picture:
            groups:
                - role:files:write
        minPlayers:
            groups:
                - role:read
                - role:list
                - role:write
                - homepage:read
        maxPerGame:
            groups:
                - role:read
                - role:list
                - role:write
                - homepage:read
        teams:
            groups:
                - role:read
                - role:list
                - role:write
                - me:player:read
                - homepage:read
