services:
  php:
    depends_on:
      - db
    build:
      context: ./api
      target: dev
    volumes:
      - ./api:/srv
    networks:
      - mercure
      - api

  web:
    depends_on:
      - php
    build:
      context: ./api
      dockerfile: ./api/.devops/nginx/Dockerfile
    volumes:
      - ./api/public:/srv/public
    networks:
      - api
      - front_ssr

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - mercure

  node:
    build:
      context: ./front
      target: dev
    volumes:
      - ./front:/app
    networks:
      - front_ssr

  db:
    image: mariadb:11.8
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garoloup
    networks:
      - api

  mailbox:
    image: mailhog/mailhog
    networks:
      - api

volumes:
  db_data:
  mercure_data:
  mercure_config:

networks:
  mercure:
  api:
  front_ssr:
