App\Entity\Game\Period\Action\InterruptAction\CoupleDeathAction:
    attributes:
        targetPlayerId:
            groups:
                - game:read
        secondaryPlayerId:
            groups:
                - game:read
        revealedRole:
            groups:
                - game:read
