<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260706195708 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ballot (id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, vote_id BINARY(16) NOT NULL, player_id BINARY(16) NOT NULL, target_id BINARY(16) NOT NULL, INDEX IDX_D59CE9BD72DCDAFC (vote_id), INDEX IDX_D59CE9BD99E6F5DF (player_id), INDEX IDX_D59CE9BD158E0B66 (target_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE close_game_invitation_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE composition (id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE configuration (with_game_master TINYINT NOT NULL, with_random_dispatch TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, composition_id BINARY(16) DEFAULT NULL, UNIQUE INDEX UNIQ_A5E2A5D787A2E12 (composition_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE create_game_event (max_players INT NOT NULL, max_time_for_discussion INT NOT NULL, public TINYINT NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE cupidon_role (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE cupidon_setup_event (first_lover_id VARCHAR(36) NOT NULL, second_lover_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE day (number INT NOT NULL, resolved TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, game_id BINARY(16) NOT NULL, INDEX IDX_E5A02990E48FD905 (game_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE day_action (id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, role_source VARCHAR(255) DEFAULT NULL, team_source VARCHAR(255) DEFAULT NULL, day_id BINARY(16) NOT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_E012674F9C24126 (day_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE game (initialisation_step VARCHAR(255) NOT NULL, runtime_step VARCHAR(255) DEFAULT NULL, interrupted_runtime_step VARCHAR(255) DEFAULT NULL, interrupted_by_role VARCHAR(255) DEFAULT NULL, step_end_at DATETIME DEFAULT NULL, winning_team VARCHAR(255) DEFAULT NULL, join_code VARCHAR(8) NOT NULL, max_players INT NOT NULL, max_time_for_discussion INT NOT NULL, public TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, host_id BINARY(16) NOT NULL, game_master_id BINARY(16) DEFAULT NULL, configuration_id BINARY(16) NOT NULL, night_workflow_id BINARY(16) DEFAULT NULL, day_workflow_id BINARY(16) DEFAULT NULL, UNIQUE INDEX UNIQ_232B318C1FB8D185 (host_id), UNIQUE INDEX UNIQ_232B318CC1151A13 (game_master_id), UNIQUE INDEX UNIQ_232B318C73F32DD8 (configuration_id), UNIQUE INDEX UNIQ_232B318CAF648A3 (night_workflow_id), UNIQUE INDEX UNIQ_232B318C3A36637F (day_workflow_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE game_event (game_id VARCHAR(255) NOT NULL, player_username VARCHAR(255) NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE game_role (type VARCHAR(255) NOT NULL, is_setup TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, role_id BINARY(16) DEFAULT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_BC7CE646D60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE game_role_dispatch_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE hunter_role (has_shot TINYINT NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE hunter_shoot_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE infect_action (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE infect_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE infect_father_role (infection_available TINYINT NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE infected_role (original_role_id BINARY(16) NOT NULL, id BINARY(16) NOT NULL, INDEX IDX_3AFBB0450838C5B (original_role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE join_game_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE launch_game_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE leave_game_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE lover_role (partner_player_id VARCHAR(36) NOT NULL, original_role_id BINARY(16) NOT NULL, id BINARY(16) NOT NULL, INDEX IDX_92BE980E50838C5B (original_role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE murder_action (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE night (number INT NOT NULL, resolved TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, game_id BINARY(16) NOT NULL, INDEX IDX_11DA0F97E48FD905 (game_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE night_action (id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, role_source VARCHAR(255) DEFAULT NULL, team_source VARCHAR(255) DEFAULT NULL, night_id BINARY(16) NOT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_4E26C6747F834C51 (night_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE player (dead TINYINT NOT NULL, afk_count INT NOT NULL, team VARCHAR(255) DEFAULT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, user_id BINARY(16) DEFAULT NULL, temp_user_id BINARY(16) DEFAULT NULL, game_id BINARY(16) DEFAULT NULL, role_id BINARY(16) DEFAULT NULL, INDEX IDX_98197A65A76ED395 (user_id), INDEX IDX_98197A651FA4E70A (temp_user_id), INDEX IDX_98197A65E48FD905 (game_id), INDEX IDX_98197A65D60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE re_open_game_invitation_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE refresh_token (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, id INT AUTO_INCREMENT NOT NULL, UNIQUE INDEX UNIQ_C74F2195C74F2195 (refresh_token), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reset_configuration_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reset_game_master_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE reset_role_dispatch_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE role (type VARCHAR(255) DEFAULT NULL, name VARCHAR(64) NOT NULL, description LONGTEXT NOT NULL, ability LONGTEXT DEFAULT NULL, picture_name VARCHAR(255) DEFAULT NULL, min_players INT DEFAULT NULL, max_per_game INT DEFAULT NULL, teams LONGTEXT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_57698A6A8CDE5729 (type), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE role_entry (count INT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, composition_id BINARY(16) NOT NULL, role_id BINARY(16) NOT NULL, INDEX IDX_DCFD755F87A2E12 (composition_id), INDEX IDX_DCFD755FD60322AC (role_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE save_action (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE seer_reveal_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE seer_role (last_observed_player_id VARCHAR(36) DEFAULT NULL, last_observed_role VARCHAR(255) DEFAULT NULL, observed_roles JSON NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE set_game_configuration_event (with_game_master TINYINT NOT NULL, with_random_dispatch TINYINT NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE set_game_master_event (target_player_id VARCHAR(255) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE temp_user (username VARCHAR(255) NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, roles JSON NOT NULL, ip VARCHAR(255) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE time_up_game_event (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE user (username VARCHAR(255) NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, roles JSON NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, reset_token VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE villager_role (id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE vote (number INT NOT NULL, resolved TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, game_id BINARY(16) NOT NULL, INDEX IDX_5A108564E48FD905 (game_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE vote_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE werewolf_role (target_player_id VARCHAR(36) DEFAULT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE werewolf_vote_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE wild_child_role (model_player_id VARCHAR(36) DEFAULT NULL, transformed TINYINT NOT NULL, target_player_id VARCHAR(36) DEFAULT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE wild_child_setup_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE witch_poison_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE witch_role (heal_potion_available TINYINT NOT NULL, poison_potion_available TINYINT NOT NULL, acted_this_night TINYINT NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE witch_save_event (target_player_id VARCHAR(36) NOT NULL, id BINARY(16) NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE workflow (steps JSON NOT NULL, current INT NOT NULL, current_turn JSON NOT NULL, completed TINYINT NOT NULL, id BINARY(16) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ballot ADD CONSTRAINT FK_D59CE9BD72DCDAFC FOREIGN KEY (vote_id) REFERENCES vote (id)');
        $this->addSql('ALTER TABLE ballot ADD CONSTRAINT FK_D59CE9BD99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id)');
        $this->addSql('ALTER TABLE ballot ADD CONSTRAINT FK_D59CE9BD158E0B66 FOREIGN KEY (target_id) REFERENCES player (id)');
        $this->addSql('ALTER TABLE close_game_invitation_event ADD CONSTRAINT FK_9E6235E7BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE configuration ADD CONSTRAINT FK_A5E2A5D787A2E12 FOREIGN KEY (composition_id) REFERENCES composition (id)');
        $this->addSql('ALTER TABLE create_game_event ADD CONSTRAINT FK_1AD0C1CCBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cupidon_role ADD CONSTRAINT FK_7A2AC54ABF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cupidon_setup_event ADD CONSTRAINT FK_E2F204EBBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE day ADD CONSTRAINT FK_E5A02990E48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE day_action ADD CONSTRAINT FK_E012674F9C24126 FOREIGN KEY (day_id) REFERENCES day (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C1FB8D185 FOREIGN KEY (host_id) REFERENCES player (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318CC1151A13 FOREIGN KEY (game_master_id) REFERENCES player (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C73F32DD8 FOREIGN KEY (configuration_id) REFERENCES configuration (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318CAF648A3 FOREIGN KEY (night_workflow_id) REFERENCES workflow (id)');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C3A36637F FOREIGN KEY (day_workflow_id) REFERENCES workflow (id)');
        $this->addSql('ALTER TABLE game_role ADD CONSTRAINT FK_BC7CE646D60322AC FOREIGN KEY (role_id) REFERENCES role (id)');
        $this->addSql('ALTER TABLE game_role_dispatch_event ADD CONSTRAINT FK_87E7BF06BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hunter_role ADD CONSTRAINT FK_7E418FF5BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hunter_shoot_event ADD CONSTRAINT FK_39D39D4FBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infect_action ADD CONSTRAINT FK_A6B92C09BF396750 FOREIGN KEY (id) REFERENCES night_action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infect_event ADD CONSTRAINT FK_409689ECBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infect_father_role ADD CONSTRAINT FK_EE6A0EF8BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infected_role ADD CONSTRAINT FK_3AFBB0450838C5B FOREIGN KEY (original_role_id) REFERENCES game_role (id)');
        $this->addSql('ALTER TABLE infected_role ADD CONSTRAINT FK_3AFBB04BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE join_game_event ADD CONSTRAINT FK_61FF5DD1BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE launch_game_event ADD CONSTRAINT FK_5690F2A0BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE leave_game_event ADD CONSTRAINT FK_B9020AD0BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE lover_role ADD CONSTRAINT FK_92BE980E50838C5B FOREIGN KEY (original_role_id) REFERENCES game_role (id)');
        $this->addSql('ALTER TABLE lover_role ADD CONSTRAINT FK_92BE980EBF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE murder_action ADD CONSTRAINT FK_5F12A317BF396750 FOREIGN KEY (id) REFERENCES night_action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE night ADD CONSTRAINT FK_11DA0F97E48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE night_action ADD CONSTRAINT FK_4E26C6747F834C51 FOREIGN KEY (night_id) REFERENCES night (id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A651FA4E70A FOREIGN KEY (temp_user_id) REFERENCES temp_user (id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65E48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65D60322AC FOREIGN KEY (role_id) REFERENCES game_role (id)');
        $this->addSql('ALTER TABLE re_open_game_invitation_event ADD CONSTRAINT FK_8337E0E5BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_configuration_event ADD CONSTRAINT FK_8F46C942BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_game_master_event ADD CONSTRAINT FK_1C4D7DC8BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reset_role_dispatch_event ADD CONSTRAINT FK_56398167BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_entry ADD CONSTRAINT FK_DCFD755F87A2E12 FOREIGN KEY (composition_id) REFERENCES composition (id)');
        $this->addSql('ALTER TABLE role_entry ADD CONSTRAINT FK_DCFD755FD60322AC FOREIGN KEY (role_id) REFERENCES role (id)');
        $this->addSql('ALTER TABLE save_action ADD CONSTRAINT FK_A434ABFBF396750 FOREIGN KEY (id) REFERENCES night_action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seer_reveal_event ADD CONSTRAINT FK_BDC98F16BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seer_role ADD CONSTRAINT FK_E4268785BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE set_game_configuration_event ADD CONSTRAINT FK_E4473CFABF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE set_game_master_event ADD CONSTRAINT FK_CD7A9ACEBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_up_game_event ADD CONSTRAINT FK_56568D2BF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE villager_role ADD CONSTRAINT FK_F3B7ADE2BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564E48FD905 FOREIGN KEY (game_id) REFERENCES game (id)');
        $this->addSql('ALTER TABLE vote_event ADD CONSTRAINT FK_6AC7686CBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE werewolf_role ADD CONSTRAINT FK_2A5ED8F1BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE werewolf_vote_event ADD CONSTRAINT FK_6E60295CBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wild_child_role ADD CONSTRAINT FK_3D8CFAE6BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wild_child_setup_event ADD CONSTRAINT FK_6E71023BBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE witch_poison_event ADD CONSTRAINT FK_45C8D07ABF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE witch_role ADD CONSTRAINT FK_BD528821BF396750 FOREIGN KEY (id) REFERENCES game_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE witch_save_event ADD CONSTRAINT FK_9A09FCDEBF396750 FOREIGN KEY (id) REFERENCES game_event (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE admin DROP FOREIGN KEY FK_880E0D76BF396750');
        $this->addSql('ALTER TABLE ballot DROP FOREIGN KEY FK_D59CE9BD72DCDAFC');
        $this->addSql('ALTER TABLE ballot DROP FOREIGN KEY FK_D59CE9BD99E6F5DF');
        $this->addSql('ALTER TABLE ballot DROP FOREIGN KEY FK_D59CE9BD158E0B66');
        $this->addSql('ALTER TABLE close_game_invitation_event DROP FOREIGN KEY FK_9E6235E7BF396750');
        $this->addSql('ALTER TABLE configuration DROP FOREIGN KEY FK_A5E2A5D787A2E12');
        $this->addSql('ALTER TABLE create_game_event DROP FOREIGN KEY FK_1AD0C1CCBF396750');
        $this->addSql('ALTER TABLE cupidon_role DROP FOREIGN KEY FK_7A2AC54ABF396750');
        $this->addSql('ALTER TABLE cupidon_setup_event DROP FOREIGN KEY FK_E2F204EBBF396750');
        $this->addSql('ALTER TABLE day DROP FOREIGN KEY FK_E5A02990E48FD905');
        $this->addSql('ALTER TABLE day_action DROP FOREIGN KEY FK_E012674F9C24126');
        $this->addSql('ALTER TABLE game DROP FOREIGN KEY FK_232B318C1FB8D185');
        $this->addSql('ALTER TABLE game DROP FOREIGN KEY FK_232B318CC1151A13');
        $this->addSql('ALTER TABLE game DROP FOREIGN KEY FK_232B318C73F32DD8');
        $this->addSql('ALTER TABLE game DROP FOREIGN KEY FK_232B318CAF648A3');
        $this->addSql('ALTER TABLE game DROP FOREIGN KEY FK_232B318C3A36637F');
        $this->addSql('ALTER TABLE game_role DROP FOREIGN KEY FK_BC7CE646D60322AC');
        $this->addSql('ALTER TABLE game_role_dispatch_event DROP FOREIGN KEY FK_87E7BF06BF396750');
        $this->addSql('ALTER TABLE hunter_role DROP FOREIGN KEY FK_7E418FF5BF396750');
        $this->addSql('ALTER TABLE hunter_shoot_event DROP FOREIGN KEY FK_39D39D4FBF396750');
        $this->addSql('ALTER TABLE infect_action DROP FOREIGN KEY FK_A6B92C09BF396750');
        $this->addSql('ALTER TABLE infect_event DROP FOREIGN KEY FK_409689ECBF396750');
        $this->addSql('ALTER TABLE infect_father_role DROP FOREIGN KEY FK_EE6A0EF8BF396750');
        $this->addSql('ALTER TABLE infected_role DROP FOREIGN KEY FK_3AFBB0450838C5B');
        $this->addSql('ALTER TABLE infected_role DROP FOREIGN KEY FK_3AFBB04BF396750');
        $this->addSql('ALTER TABLE join_game_event DROP FOREIGN KEY FK_61FF5DD1BF396750');
        $this->addSql('ALTER TABLE launch_game_event DROP FOREIGN KEY FK_5690F2A0BF396750');
        $this->addSql('ALTER TABLE leave_game_event DROP FOREIGN KEY FK_B9020AD0BF396750');
        $this->addSql('ALTER TABLE lover_role DROP FOREIGN KEY FK_92BE980E50838C5B');
        $this->addSql('ALTER TABLE lover_role DROP FOREIGN KEY FK_92BE980EBF396750');
        $this->addSql('ALTER TABLE murder_action DROP FOREIGN KEY FK_5F12A317BF396750');
        $this->addSql('ALTER TABLE night DROP FOREIGN KEY FK_11DA0F97E48FD905');
        $this->addSql('ALTER TABLE night_action DROP FOREIGN KEY FK_4E26C6747F834C51');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A65A76ED395');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A651FA4E70A');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A65E48FD905');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A65D60322AC');
        $this->addSql('ALTER TABLE re_open_game_invitation_event DROP FOREIGN KEY FK_8337E0E5BF396750');
        $this->addSql('ALTER TABLE reset_configuration_event DROP FOREIGN KEY FK_8F46C942BF396750');
        $this->addSql('ALTER TABLE reset_game_master_event DROP FOREIGN KEY FK_1C4D7DC8BF396750');
        $this->addSql('ALTER TABLE reset_role_dispatch_event DROP FOREIGN KEY FK_56398167BF396750');
        $this->addSql('ALTER TABLE role_entry DROP FOREIGN KEY FK_DCFD755F87A2E12');
        $this->addSql('ALTER TABLE role_entry DROP FOREIGN KEY FK_DCFD755FD60322AC');
        $this->addSql('ALTER TABLE save_action DROP FOREIGN KEY FK_A434ABFBF396750');
        $this->addSql('ALTER TABLE seer_reveal_event DROP FOREIGN KEY FK_BDC98F16BF396750');
        $this->addSql('ALTER TABLE seer_role DROP FOREIGN KEY FK_E4268785BF396750');
        $this->addSql('ALTER TABLE set_game_configuration_event DROP FOREIGN KEY FK_E4473CFABF396750');
        $this->addSql('ALTER TABLE set_game_master_event DROP FOREIGN KEY FK_CD7A9ACEBF396750');
        $this->addSql('ALTER TABLE time_up_game_event DROP FOREIGN KEY FK_56568D2BF396750');
        $this->addSql('ALTER TABLE villager_role DROP FOREIGN KEY FK_F3B7ADE2BF396750');
        $this->addSql('ALTER TABLE vote DROP FOREIGN KEY FK_5A108564E48FD905');
        $this->addSql('ALTER TABLE vote_event DROP FOREIGN KEY FK_6AC7686CBF396750');
        $this->addSql('ALTER TABLE werewolf_role DROP FOREIGN KEY FK_2A5ED8F1BF396750');
        $this->addSql('ALTER TABLE werewolf_vote_event DROP FOREIGN KEY FK_6E60295CBF396750');
        $this->addSql('ALTER TABLE wild_child_role DROP FOREIGN KEY FK_3D8CFAE6BF396750');
        $this->addSql('ALTER TABLE wild_child_setup_event DROP FOREIGN KEY FK_6E71023BBF396750');
        $this->addSql('ALTER TABLE witch_poison_event DROP FOREIGN KEY FK_45C8D07ABF396750');
        $this->addSql('ALTER TABLE witch_role DROP FOREIGN KEY FK_BD528821BF396750');
        $this->addSql('ALTER TABLE witch_save_event DROP FOREIGN KEY FK_9A09FCDEBF396750');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE ballot');
        $this->addSql('DROP TABLE close_game_invitation_event');
        $this->addSql('DROP TABLE composition');
        $this->addSql('DROP TABLE configuration');
        $this->addSql('DROP TABLE create_game_event');
        $this->addSql('DROP TABLE cupidon_role');
        $this->addSql('DROP TABLE cupidon_setup_event');
        $this->addSql('DROP TABLE day');
        $this->addSql('DROP TABLE day_action');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_event');
        $this->addSql('DROP TABLE game_role');
        $this->addSql('DROP TABLE game_role_dispatch_event');
        $this->addSql('DROP TABLE hunter_role');
        $this->addSql('DROP TABLE hunter_shoot_event');
        $this->addSql('DROP TABLE infect_action');
        $this->addSql('DROP TABLE infect_event');
        $this->addSql('DROP TABLE infect_father_role');
        $this->addSql('DROP TABLE infected_role');
        $this->addSql('DROP TABLE join_game_event');
        $this->addSql('DROP TABLE launch_game_event');
        $this->addSql('DROP TABLE leave_game_event');
        $this->addSql('DROP TABLE lover_role');
        $this->addSql('DROP TABLE murder_action');
        $this->addSql('DROP TABLE night');
        $this->addSql('DROP TABLE night_action');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE re_open_game_invitation_event');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE reset_configuration_event');
        $this->addSql('DROP TABLE reset_game_master_event');
        $this->addSql('DROP TABLE reset_role_dispatch_event');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_entry');
        $this->addSql('DROP TABLE save_action');
        $this->addSql('DROP TABLE seer_reveal_event');
        $this->addSql('DROP TABLE seer_role');
        $this->addSql('DROP TABLE set_game_configuration_event');
        $this->addSql('DROP TABLE set_game_master_event');
        $this->addSql('DROP TABLE temp_user');
        $this->addSql('DROP TABLE time_up_game_event');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE villager_role');
        $this->addSql('DROP TABLE vote');
        $this->addSql('DROP TABLE vote_event');
        $this->addSql('DROP TABLE werewolf_role');
        $this->addSql('DROP TABLE werewolf_vote_event');
        $this->addSql('DROP TABLE wild_child_role');
        $this->addSql('DROP TABLE wild_child_setup_event');
        $this->addSql('DROP TABLE witch_poison_event');
        $this->addSql('DROP TABLE witch_role');
        $this->addSql('DROP TABLE witch_save_event');
        $this->addSql('DROP TABLE workflow');
    }
}
