App\Entity\Game\Period\Action\NightAction\MurderAction:
    attributes:
        targetPlayerId:
            groups:
                - game:read
        revealedRole:
            groups:
                - game:read
