App\Entity\Game\Game:
    attributes:
        id:
            groups:
                - me:read
                - game:read
        step:
            groups:
                - me:read
                - game:read
        joinCode:
            groups:
                - game:read
        players:
            groups:
                - game:read
