App\Entity\Game\Game:
    attributes:
        id:
            groups:
                - me:read
                - me:player:read
                - game:read
        step:
            groups:
                - me:read
                - game:read
        joinCode:
            groups:
                - game:read
        players:
            groups:
                - game:read
        configuration:
            groups:
                - game:read
        maxPlayers:
            groups:
                - game:read
        maxTimeForDiscussion:
            groups:
                - game:read
        public:
            groups:
                - game:read
