App\Entity\Game\Game:
    attributes:
        id:
            groups:
                - me:read
                - me:player:read
                - game:read
                - homepage:read
        initialisationStep:
            groups:
                - game:read
        runtimeStep:
            groups:
                - game:read
        globalStep:
            groups:
                - game:read
        joinCode:
            groups:
                - game:read
                - homepage:read
        players:
            groups:
                - game:read
                - homepage:read
        configuration:
            groups:
                - game:read
        maxPlayers:
            groups:
                - game:read
                - homepage:read
        maxTimeForDiscussion:
            groups:
                - game:read
                - homepage:read
        public:
            groups:
                - game:read
        stepEndAt:
            groups:
                - game:read
        winningTeam:
            groups:
                - game:read
        nights:
            groups:
                - game:read
        days:
            groups:
                - game:read
        votes:
            groups:
                - game:read
