App\Entity\Game\Player:
    attributes:
        id:
            groups:
                - me:read
                - game:read
        user:
            groups:
                - me:read
                - game:read
        tempUser:
            groups:
                - me:read
                - game:read
        dead:
            groups:
                - me:read
                - game:read
        game:
            groups:
                - me:read
        host:
            groups:
                - me:read
