App\Entity\Game\Player:
    attributes:
        id:
            groups:
                - me:read
                - me:player:read
                - game:read
                - werewolf-team:read
        user:
            groups:
                - me:read
                - me:player:read
                - game:read
        tempUser:
            groups:
                - me:read
                - me:player:read
                - game:read
        dead:
            groups:
                - me:read
                - me:player:read
                - game:read
        game:
            groups:
                - me:read
                - me:player:read
        host:
            groups:
                - me:read
                - me:player:read
        gameMaster:
            groups:
                - me:read
                - me:player:read
        role:
            groups:
                - me:player:read
        username:
            groups:
                - me:player:read
                - werewolf-team:read
        afkCount:
            groups:
                - me:player:read
