# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.ssr_public_uploads_path: '%env(string:SSR_PUBLIC_UPLOADS_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $frontResetUrl: '%env(string:FRONT_RESET_URL)%'
            string $publicUploadsPath: '%env(string:PUBLIC_UPLOADS_PATH)%'
            string $ssrPublicUploadsPath: '%env(string:SSR_PUBLIC_UPLOADS_PATH)%'
            int $minimumPlayers: '%env(int:MINIMUM_PLAYERS)%'
            int $setupDuration: '%env(int:SETUP_DURATION)%'
            int $nightStepDuration: '%env(int:NIGHT_STEP_DURATION)%'
            int $voteDuration: '%env(int:VOTE_DURATION)%'
            int $afkThreshold: '%env(int:AFK_THRESHOLD)%'

    _instanceof:
        App\Domain\GameEvent\Interface\GameEventApplicatorInterface:
            tags: ['game_event.applicator']
        App\Domain\WinCondition\Interface\WinConditionCheckerInterface:
            tags: ['win_condition.checker']

    App\Fixtures\:
        resource: '../fixtures'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'
            - '../src/Domain/Command/**/*Command.php'
            - '../src/Api/Model/'

    App\Domain\GameEvent\GameEventDispatcher:
        arguments:
            $applicators: !tagged_iterator game_event.applicator

    App\Domain\WinCondition\WinDetector:
        arguments:
            $checkers: !tagged_iterator win_condition.checker

