App\Entity\Game\Period\Day:
    attributes:
        id:
            groups:
                - game:read
        number:
            groups:
                - game:read
        resolved:
            groups:
                - game:read
        actions:
            groups:
                - game:read
