App\Entity\Game\Role\GameRole:
    attributes:
        role:
            groups:
                - me:player:read
        type:
            groups:
                - me:player:read

App\Entity\Game\Role\VillagerRole:
    attributes:
        friendId:
            groups:
                - me:player:read

App\Entity\Game\Role\SeerRole:
    attributes:
        lastObservedPlayerId:
            groups:
                - me:player:read
        lastObservedRole:
            groups:
                - me:player:read
        observedRoles:
            groups:
                - me:player:read

App\Entity\Game\Role\WitchRole:
    attributes:
        healPotionAvailable:
            groups:
                - me:player:read
        poisonPotionAvailable:
            groups:
                - me:player:read
