import { cva } from 'class-variance-authority';

export const typographyCva = cva('antialiased', {
  variants: {
    variant: {
      body: 'text-[1rem] leading-[1.5rem]',
      'body-sm': 'text-[0.875rem] leading-[1.375rem]',
      'body-xs': 'text-[0.75rem] leading-[1.25rem]',
      'heading-1': 'text-[2.5rem] leading-[3rem] xs:text-[4rem] xs:leading-[4.5rem] sm:text-[6.5rem] sm:leading-[7rem]',
      'heading-2': 'text-[2rem] leading-[2.5rem] sm:text-[4rem] sm:leading-[4.5rem]',
      'heading-3': 'text-[1.5rem] leading-[2rem] sm:text-[2rem] sm:leading-[2.5rem]',
      subtitle: 'text-[1.375rem] leading-[1.75rem]',
      button: 'text-[1rem] leading-[1.5rem]',
      tag: 'text-[0.625rem] leading-[1.25rem]',
      controlled: '',
    },
    textColor: {
      controlled: 'text-inherit',
      text: 'text-foreground',
      light: 'text-light',
      dark: 'text-dark',
      primary: 'text-primary',
      secondary: 'text-secondary',
      accent: 'text-accent',
      error: 'text-error',
      success: 'text-success',
      'neutral-200': 'text-neutral-200',
      'neutral-300': 'text-neutral-300',
      'neutral-400': 'text-neutral-400',
      'neutral-500': 'text-neutral-500',
      'neutral-600': 'text-neutral-600',
      'neutral-700': 'text-neutral-700',
      'neutral-800': 'text-neutral-800',
    },
    bold: { true: 'font-bold' },
    center: { true: 'text-center' },
    underline: { true: 'underline' },
    uppercase: { true: 'uppercase' },
    ellipsis: { true: 'truncate' },
    special: { true: 'font-special' },
  },
  compoundVariants: [
    {
      special: false,
      variant: ['heading-1', 'heading-2', 'heading-3', 'subtitle'],
      class: 'font-title',
    },
    {
      special: false,
      variant: ['body', 'body-sm', 'body-xs', 'controlled', 'button'],
      class: 'font-normal',
    },
  ],
  defaultVariants: {
    variant: 'body',
    textColor: 'text',
    bold: false,
    center: false,
    underline: false,
    ellipsis: false,
    special: false,
  },
});
